### ISSUE TITLE
Create login/signin page

### ISSUE THREAD

**Issue by drodmun** [drodmun/HIIT-Timer#18]
Use firebase for authentication enabling google, facebook and email

**Comment by raffidahmad** [comment]
Login and signup are up and running with firebase. 
Styling to be performed after making app functional.

**Comment by drodmun** [comment]
There is no Pull Request to merge the code, is there?

**Comment by raffidahmad** [comment]
No, I still want to do more changes.

**Comment by raffidahmad** [comment]
I want to keep this development branch separate till everything is implemented. You can test this branch locally.

**Comment by drodmun** [comment]
awesome, but keep it open untill merged please
