### ISSUE TITLE
Add possibility to share a set

### ISSUE THREAD

**Issue by drodmun** [drodmun/HIIT-Timer#21]
Depends on #18 

- There should be a possibility to share the current set on screen by email, whatsapp, social... 
- The set should appear loaded to be used directly
- If the recipient (who you share it with) is a logged user, the possibility to save it will be enabled, if is not logged, on "clicked save" should show the login/signin page

**Comment by raffidahmad** [comment]
kindly clarify if a set means a full preset or a single set on the screen with X number of rounds, cooldown, prep etc

**Comment by drodmun** [comment]
kindly clarify if a set means ~~a full preset~~ or a **single set on the screen with X number of rounds, cooldown, prep etc**
