### ISSUE TITLE
Modify UI to enable Light/Dark mode

### ISSUE THREAD

**Issue by drodmun** [drodmun/HIIT-Timer#22]
Currently the mode seems "dark" with the pop-up/modals being light

- Separate UI into Light and Dark mode
- Enable swith with animation like [this library](https://www.npmjs.com/package/react-toggle-dark-mode)
- Store locally the selected view to use by default on future visits

**Comment by drodmun** [comment]
#18 Apparently, code being merged in the branch of the login/signin ticket

**Comment by raffidahmad** [comment]
oh that's probably because I made this branch from that issue? 
I'll make a new branch as soon as I complete the login and ui.

**Comment by raffidahmad** [comment]
Dark mode integrated.
