### ISSUE TITLE
Replace text explain "Set" configuration with a visual representation

### ISSUE THREAD

**Issue by drodmun** [drodmun/HIIT-Timer#23]

**Comment by drodmun** [comment]
![Example1](https://fiverr-res.cloudinary.com/image/upload/t_collaboration_hd,q_auto,f_auto/v1/secured-attachments/message/order_attachments/6ce8f91124293bc0bde6272824c72b98-1662740220966/image.png?__cld_token__=exp=1662762511~hmac=9b18dbc3844ee8c3212a1fafe6c2ee8a0c7fac6365b38d6563b459ab0ae78307)
![Example2](https://fiverr-res.cloudinary.com/image/upload/t_collaboration_hd,q_auto,f_auto/v1/secured-attachments/message/order_attachments/6ce8f91124293bc0bde6272824c72b98-1662740245682/image.png?__cld_token__=exp=1662762511~hmac=45d11c6e6c8603b488e290f056f627431154d4cbd6c372a8bfba6d1f16216da5)
![Example3](https://fiverr-res.cloudinary.com/image/upload/t_collaboration_hd,q_auto,f_auto/v1/secured-attachments/message/order_attachments/6ce8f91124293bc0bde6272824c72b98-1662740195531/image.png?__cld_token__=exp=1662762511~hmac=fbeddc7aba74968ec5c2f93f965d4041c5aff5d8f27a35dde476dd78d5c8aad9)

**Comment by raffidahmad** [comment]
Visuals replaced.
